spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch_edu?serverTimezone=Asia/Seoul
    username: admin
    password: admin
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

  